# Generated by Django 5.1.15 on 2026-04-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0026_alter_userprofile_role"),
        ('faculty_assignments', '0002_delete_mentorship'),
    ]

    # REPLACE the operations block with this structure:
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Mentorship',
                    fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentees",
                        to="core.userprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student",)},
                    },
                ),
            ],
            database_operations=[
                # This executes the actual MySQL table rename preserving your data!
                migrations.RunSQL(
                    sql="ALTER TABLE faculty_assignments_mentorship RENAME TO counselling_mentorship;",
                    reverse_sql="ALTER TABLE counselling_mentorship RENAME TO faculty_assignments_mentorship;"
                )
            ]
        )
    ]
