# Generated by Django 5.1.15 on 2026-04-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_studentgroup_subject_alter_course_subject_type"),
        ("counselling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenteeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("pin_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "father_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "mother_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "guardian_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "hobbies",
                    models.TextField(
                        blank=True, help_text="Hobbies / Interests", null=True
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True, help_text="Achievements & Victories", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_profile",
                        to="core.student",
                    ),
                ),
            ],
        ),
    ]
