# backend/core/serializers.py

from rest_framework import serializers
from dj_rest_auth.serializers import UserDetailsSerializer, PasswordResetSerializer, PasswordResetConfirmSerializer
from dj_rest_auth.registration.serializers import RegisterSerializer
from allauth.account.forms import ResetPasswordForm as AllAuthPasswordResetForm
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_str
from django.contrib.auth.password_validation import validate_password

from django.contrib.auth.models import User
from .models import UserProfile, Department, Organization, AcademicYear



from .models import Course


from .models import Student, StudentGroup

# 1. User Details (for /user/me/)
class CustomUserDetailsSerializer(UserDetailsSerializer):
    role = serializers.CharField(source="profile.role", read_only=True)
    organization_name = serializers.CharField(source="profile.organization.name", read_only=True, allow_null=True)
    is_setup_complete = serializers.BooleanField(source="profile.is_setup_complete", read_only=True)
    permissions = serializers.JSONField(source="profile.permissions", read_only=True)

    class Meta(UserDetailsSerializer.Meta):
        fields = UserDetailsSerializer.Meta.fields + (
            'role', 'organization_name', 'is_setup_complete', 'permissions'
        )

# 2. Password Reset Request (Sending the Email)
class CustomPasswordResetSerializer(PasswordResetSerializer):
    """
    Forces dj-rest-auth to use the AllAuth form. 
    This allows Google users (who have no password) to reset/set one.
    """
    @property
    def password_reset_form_class(self):
        return AllAuthPasswordResetForm

# 3. Password Reset Confirm (Setting the New Password)
class CustomPasswordResetConfirmSerializer(PasswordResetConfirmSerializer):
    """
    Custom validation logic to handle UID/Token checks manually, 
    preventing 'Invalid Value' errors on valid requests.
    """
    def validate(self, attrs):
        # A. Decode UID
        try:
            uid_b64 = attrs.get('uid')
            uid = force_str(urlsafe_base64_decode(uid_b64))
            self.user = get_user_model().objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
            raise serializers.ValidationError({'uid': ['Invalid UID']})

        # B. Check Token
        token = attrs.get('token')
        if not default_token_generator.check_token(self.user, token):
            raise serializers.ValidationError({'token': ['Invalid or expired link. Please request a new one.']})

        # C. Check Passwords Match
        if attrs.get('new_password1') != attrs.get('new_password2'):
            raise serializers.ValidationError({'new_password1': ['The two password fields didn’t match.']})

        # D. Check if Password is SAME as Old Password
        if self.user.check_password(attrs.get('new_password1')):
             raise serializers.ValidationError({'new_password1': ['Your new password cannot be the same as your old password.']})

        # E. Check Password Complexity (Length, Digits, Commonality)
        try:
            validate_password(attrs.get('new_password1'), self.user)
        except Exception as e:
            # e.messages is a list of strings from Django's validators
            raise serializers.ValidationError({'new_password1': list(e.messages)})

        return attrs

    def save(self):
        self.user.set_password(self.validated_data['new_password1'])
        self.user.save()
        return self.user

class CustomRegisterSerializer(RegisterSerializer):
    first_name = serializers.CharField(required=False)
    last_name = serializers.CharField(required=False)
    username = serializers.CharField(required=False) 

    def custom_signup(self, request, user):
        """
        This method is called after the user is created but before the response is returned.
        We use it to save the extra fields passed from the frontend.
        """
        user.first_name = self.validated_data.get('first_name', '')
        user.last_name = self.validated_data.get('last_name', '')
        
        # If the frontend sent a username, save it. 
        # Otherwise, one might have been auto-generated by AllAuth.
        if self.validated_data.get('username'):
            user.username = self.validated_data.get('username')
            
        user.save()




# --- 1. Structural Serializers (For Dropdowns) ---

class DepartmentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Department
        fields = ['id', 'name', 'code']

class AcademicYearSerializer(serializers.ModelSerializer):
    class Meta:
        model = AcademicYear
        fields = ['id', 'name', 'start_date', 'end_date', 'is_active']

# --- 2. Faculty Serializer (The Complex One) ---

class FacultySerializer(serializers.ModelSerializer):
    """
    Serializes the Faculty Profile + Linked User Info.
    """
    email = serializers.EmailField(source='user.email', read_only=True)
    full_name = serializers.CharField(source='user.first_name', read_only=True) # Using first_name as full name container for now
    department_name = serializers.CharField(source='department.name', read_only=True)

    class Meta:
        model = UserProfile
        fields = [
            'id', 
            'email', 
            'full_name', 
            'department', 
            'department_name',
            'designation', 
            'phone_number', 
            'role',
            'is_setup_complete',
            'profile_picture'
        ]

class AddFacultySerializer(serializers.Serializer):
    """
    Input Validation for the 'Add Faculty' Form.
    """
    email = serializers.EmailField()
    full_name = serializers.CharField(max_length=255)
    designation = serializers.CharField(max_length=100)
    department_id = serializers.IntegerField()
    phone_number = serializers.CharField(max_length=15, required=False, allow_blank=True)
    profile_picture = serializers.ImageField(required=False, allow_null=True)

    def validate_email(self, value):
        # We allow existing users (e.g., if they were Staff, we upgrade them)
        # But we warn if they are already FACULTY
        user_qs = User.objects.filter(email=value)
        if user_qs.exists():
            user = user_qs.first()
            if hasattr(user, 'profile') and user.profile.role == 'FACULTY':
                raise serializers.ValidationError("This user is already registered as Faculty.")
        return value



class CourseSerializer(serializers.ModelSerializer):
    class Meta:
        model = Course
        fields = '__all__'



class StudentSerializer(serializers.ModelSerializer):
    department_name = serializers.CharField(source='department.name', read_only=True)
    academic_year_name = serializers.CharField(source='academic_year.name', read_only=True)

    class Meta:
        model = Student
        fields = '__all__'

class StudentMiniSerializer(serializers.ModelSerializer):
    class Meta:
        model = Student
        fields = ['id', 'full_name', 'enrollment_number']

class StudentGroupSerializer(serializers.ModelSerializer):
    student_count = serializers.IntegerField(source='students.count', read_only=True)
    students_list = StudentMiniSerializer(source='students', many=True, read_only=True) # <-- ADD THIS LINE
    
    class Meta:
        model = StudentGroup
        fields = '__all__'
