# Generated by Django 5.2.9 on 2025-12-31 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_student_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docusense_uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('RESULT', 'University Result'), ('REPORT', 'Academic Report')], max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Analyzing...'), ('COMPLETED', 'Analysis Ready'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=20)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
    ]
