# Generated by Django 5.1.15 on 2026-04-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculty_assignments", "0001_initial"),
    ]

    # REPLACE the operations block with this:
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Mentorship',
                ),
            ],
            # This empty list tells the database NOT to drop your live table!
            database_operations=[], 
        )
    ]
