import threading
import os
from django.core.files import File
from .models import AcademicDocument
# CHANGED: Importing the correct function name from your new local_vision.py
#from .local_vision import extract_data_local 

def trigger_analysis_background(document_id):
    """
    Called by the View to start processing without freezing the API.
    """
    thread = threading.Thread(target=_process_document_task, args=(document_id,))
    thread.daemon = True # Ensures thread dies if main server dies
    thread.start()

def _process_document_task(document_id):
    """
    The worker function that runs in the background.
    """
    try:
        doc = AcademicDocument.objects.get(id=document_id)
        doc.status = 'PROCESSING'
        doc.save()

        # Callback to print progress to your console (or you can save to DB)
        def progress_callback(percent, message):
            print(f"[Doc {document_id}] {percent}%: {message}")

        # --- CALL THE NEW OCR ENGINE ---
        # extract_data_local returns: (DataFrame, Excel_Path_String, Analytics_Dict)
        _, excel_full_path, analytics_data = extract_data_local(doc.file.path, progress_callback)

        # 1. Save Analysis Data (Pass %, SGPA stats)
        doc.analysis_data = analytics_data

        # 2. Save the Generated Excel File to the Model
        # We open the file generated by Pandas and save it to the Django FileField
        if os.path.exists(excel_full_path):
            with open(excel_full_path, 'rb') as f:
                # Assuming your model has a field named 'excel_file' or similar
                # If your field is named 'generated_file', change 'excel_file' below to that.
                doc.excel_file.save(os.path.basename(excel_full_path), File(f), save=False)

        doc.status = 'COMPLETED'
        doc.save()
        
        # Optional: Clean up the temp file if you don't want duplicates on disk
        # os.remove(excel_full_path) 

    except Exception as e:
        print(f"!!! Error processing document {document_id}: {e}")
        # Re-fetch doc to ensure we have the latest state before saving error
        doc = AcademicDocument.objects.get(id=document_id)
        doc.status = 'FAILED'
        doc.analysis_data = {'error': str(e)}
        doc.save()