# Generated by Django 5.2.9 on 2025-12-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University'), ('Coaching', 'Coaching')], default='School', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
