# Generated by Django 5.1.15 on 2026-02-15 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_student_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=50)),
                ("enrollment_number", models.CharField(max_length=50, unique=True)),
                ("aic_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "aadhar_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "name_on_aadhar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("current_semester", models.IntegerField(default=1)),
                (
                    "signature_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["enrollment_number"],
                        name="core_studen_enrollm_e873cb_idx",
                    ),
                    models.Index(
                        fields=["roll_number"], name="core_studen_roll_nu_9cbe47_idx"
                    ),
                ],
                "unique_together": {("organization", "enrollment_number")},
            },
        ),
    ]
