# Generated by Django 5.1.15 on 2026-02-19 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_dataimportlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=20)),
                ("semester", models.IntegerField()),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("THEORY", "Theory (Core)"),
                            ("LAB", "Practical / Lab"),
                            ("PRO_ELECTIVE", "Professional Elective"),
                            ("OPEN_ELECTIVE", "Open Elective"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits", models.IntegerField(default=4)),
                ("is_open_elective", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CLASS", "Whole Class"),
                            ("BATCH", "Lab Batch"),
                            ("ELECTIVE", "Elective Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("semester", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TeachingAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_hours", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Teaching Allocation",
            },
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="core_studen_enrollm_e873cb_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="core_studen_roll_nu_9cbe47_idx",
        ),
        migrations.RenameField(
            model_name="dataimportlog",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="dataimportlog",
            name="category",
        ),
        migrations.RemoveField(
            model_name="dataimportlog",
            name="file",
        ),
        migrations.RemoveField(
            model_name="dataimportlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="dataimportlog",
            name="validation_summary",
        ),
        migrations.RemoveField(
            model_name="department",
            name="config",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="permissions",
        ),
        migrations.AddField(
            model_name="dataimportlog",
            name="error_log",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataimportlog",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("STUDENT_REGISTRATION", "Student Registration"),
                    ("FACULTY_LOAD", "Faculty Workload"),
                    ("MARKS_ENTRY", "Exam Marks"),
                    ("ATTENDANCE", "Attendance Records"),
                ],
                default="STUDENT_REGISTRATION",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataimportlog",
            name="success_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dataimportlog",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(default="ECS", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="dataimportlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Processing..."),
                    ("SUCCESS", "Success"),
                    ("PARTIAL_SUCCESS", "Partial Success (Some rows failed)"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("School", "School"),
                    ("College", "College"),
                    ("University", "University"),
                ],
                default="College",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ORG_ADMIN", "Principal/HOD"),
                    ("FACULTY", "Faculty"),
                    ("STAFF", "Non-Teaching Staff"),
                    ("STUDENT", "Student"),
                ],
                default="FACULTY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="dataimportlog",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.department"
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.department"
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.studentgroup",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(blank=True, to="core.student"),
        ),
        migrations.AddField(
            model_name="teachingallocation",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="teachingallocation",
            name="faculty",
            field=models.ForeignKey(
                limit_choices_to={"role": "FACULTY"},
                on_delete=django.db.models.deletion.CASCADE,
                to="core.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teachingallocation",
            name="student_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.studentgroup"
            ),
        ),
        migrations.AddField(
            model_name="teachingallocation",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.course"
            ),
        ),
        migrations.RemoveField(
            model_name="student",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="student",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="student",
            name="mobile_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name_on_aadhar",
        ),
        migrations.RemoveField(
            model_name="student",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="student",
            name="signature_status",
        ),
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("department", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="teachingallocation",
            unique_together={("academic_year", "subject", "student_group")},
        ),
    ]
