# Generated by Django 5.1.15 on 2026-02-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_academicyear_course_studentgroup_teachingallocation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="faculty_profiles/"
            ),
        ),
    ]
