# Generated by Django 5.1.15 on 2026-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_student_academic_year_student_dob_student_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataimportlog",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="import_logs/"),
        ),
    ]
