# Generated by Django 5.1.15 on 2026-02-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_dataimportlog_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="course",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("THEORY", "Theory (Compulsory)"),
                    ("LAB", "Practical / Lab"),
                    ("PRO_ELECTIVE", "Professional Elective"),
                    ("OPEN_ELECTIVE", "Open Elective"),
                ],
                max_length=20,
            ),
        ),
    ]
