# Generated by Django 5.1.15 on 2026-02-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_course_credits_alter_course_subject_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teachingallocation",
            unique_together={("academic_year", "faculty", "subject", "student_group")},
        ),
    ]
