# Generated by Django 5.1.15 on 2026-02-21 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_teachingallocation_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachingallocation",
            name="faculty",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["FACULTY", "ORG_ADMIN", "SUPER_ADMIN"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="core.userprofile",
            ),
        ),
    ]
