# Generated by Django 5.1.15 on 2026-02-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_student_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_teaching_faculty",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Principal / Director"),
                    ("ORG_ADMIN", "Organization Admin"),
                    ("HOD", "Head of Department"),
                    ("STAFF", "Office Staff"),
                    ("FACULTY", "Teaching Faculty"),
                    ("STUDENT", "Student"),
                ],
                default="FACULTY",
                max_length=20,
            ),
        ),
    ]
