# Generated by Django 5.1.15 on 2026-03-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_userprofile_is_teaching_faculty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
