# Generated by Django 5.1.15 on 2026-03-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_otpverification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTPVerification",
        ),
    ]
