# Generated by Django 5.1.15 on 2026-03-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_course_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_active",
        ),
    ]
