# Generated by Django 5.1.15 on 2026-03-10 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_course_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="student_email_domain",
            field=models.CharField(
                blank=True, help_text="e.g. dbcegoa.ac.in", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
