# Generated by Django 5.1.15 on 2026-03-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_organization_student_email_domain_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a Batch, link it to its Master Class.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_batches",
                to="core.studentgroup",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="student_groups", to="core.student"
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("CLASS", "Master Class (Theory)"),
                    ("BATCH", "Shared Lab Batch"),
                    ("ELECTIVE", "Elective Section"),
                ],
                max_length=20,
            ),
        ),
    ]
