# Generated by Django 5.1.15 on 2026-03-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_studentgroup_parent_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.studentgroup",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(blank=True, to="core.student"),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("CLASS", "Whole Class"),
                    ("BATCH", "Lab Batch"),
                    ("ELECTIVE", "Elective Section"),
                ],
                max_length=20,
            ),
        ),
    ]
