# Generated by Django 5.1.15 on 2026-03-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_studentgroup_parent_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "code")},
        ),
    ]
