# Generated by Django 5.1.15 on 2026-03-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_department_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="even_term_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="even_term_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="odd_term_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="odd_term_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="core.organization",
            ),
        ),
    ]
