# Generated by Django 5.1.15 on 2026-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_academicyear_even_term_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Principal / Director"),
                    ("ORG_ADMIN", "Organization Admin"),
                    ("HOD", "Head of Department"),
                    ("STAFF", "Office Staff"),
                    ("FACULTY", "Teaching Faculty"),
                    ("COUNSELLOR", "Counselling Department"),
                    ("SPORTS_STAFF", "Sports Department"),
                    ("STUDENT", "Student"),
                ],
                default="FACULTY",
                max_length=20,
            ),
        ),
    ]
