# Generated by Django 5.1.15 on 2026-04-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_groups",
                to="core.course",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("THEORY", "Theory (Compulsory)"),
                    ("LAB", "Practical / Lab"),
                    ("PRO_ELECTIVE", "Professional Elective"),
                    ("OPEN_ELECTIVE", "Open Elective"),
                    ("PRO_ELECTIVE_LAB", "Professional Elective Lab"),
                ],
                max_length=20,
            ),
        ),
    ]
